[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[context.production]
  environment = { VITE_SUPABASE_URL = "$VITE_SUPABASE_URL", VITE_SUPABASE_PUBLISHABLE_KEY = "$VITE_SUPABASE_PUBLISHABLE_KEY" }
